"""mkfont.py - Bm437_IBM_VGA_8x16.otb -> src/nilterm/nilfont.h

    python tools/mkfont.py <Bm437_IBM_VGA_8x16.otb> src/nilterm/nilfont.h <preview.png>

The .otb is from the pack's linux zip ('otb - Bm (linux bitmap)/'); it is not kept in the repo.
 (256 CP437 glyphs, 8x16, one byte per row, MSB = left)
plus a 32x8-glyph preview PNG.  Font: The Ultimate Oldschool PC Font Pack by VileR (int10h.org),
CC BY-SA 4.0."""
import sys
from PIL import Image, ImageDraw, ImageFont

OTB, OUT_H, OUT_PNG = sys.argv[1], sys.argv[2], sys.argv[3]
LOW = [0x0000, 0x263A, 0x263B, 0x2665, 0x2666, 0x2663, 0x2660, 0x2022, 0x25D8, 0x25CB, 0x25D9,
       0x2642, 0x2640, 0x266A, 0x266B, 0x263C, 0x25BA, 0x25C4, 0x2195, 0x203C, 0x00B6, 0x00A7,
       0x25AC, 0x21A8, 0x2191, 0x2193, 0x2192, 0x2190, 0x221F, 0x2194, 0x25B2, 0x25BC]

def unicode_of(c):
    if c < 0x20: return LOW[c]
    if c == 0x7F: return 0x2302
    return ord(bytes([c]).decode('cp437'))

font = ImageFont.truetype(OTB, 16)

def render(u):
    """draw into a tall canvas at a fixed baseline so nothing is clipped"""
    img = Image.new('1', (16, 48), 0)
    if u:
        ImageDraw.Draw(img).text((0, 32), chr(u), font=font, fill=1, anchor='ls')
    return img

# the 8x16 cell: the full block (CP437 DB = U+2588) fills it exactly - find its rows/columns
full = render(0x2588)
ys = [y for y in range(full.height) if any(full.getpixel((x, y)) for x in range(full.width))]
xs = [x for x in range(full.width) if any(full.getpixel((x, y)) for y in range(full.height))]
top, left = ys[0], xs[0]
assert len(ys) == 16 and len(xs) == 8, ('full block is not 8x16', len(xs), len(ys))

glyphs, missing, spill = [], [], []
for c in range(256):
    u = unicode_of(c)
    img = render(u)
    lit = [(x, y) for y in range(img.height) for x in range(img.width) if img.getpixel((x, y))]
    if not lit and u not in (0, 0x20, 0xA0): missing.append((c, hex(u)))
    if any(not (left <= x < left + 8 and top <= y < top + 16) for x, y in lit): spill.append(c)
    rows = []
    for y in range(16):
        b = 0
        for x in range(8):
            if img.getpixel((left + x, top + y)): b |= 0x80 >> x
        rows.append(b)
    glyphs.append(rows)
print('cell top/left in canvas:', top, left, ' glyphs outside the cell:', spill)

with open(OUT_H, 'w', newline='\n') as f:
    f.write('/* nilfont.h - IBM VGA 8x16 (CP437), 256 glyphs x 16 rows, MSB = leftmost pixel.\n'
            ' * Generated by tools/mkfont.py from Bm437_IBM_VGA_8x16.otb, part of "The Ultimate\n'
            ' * Oldschool PC Font Pack" by VileR, https://int10h.org/oldschool-pc-fonts/ ,\n'
            ' * licensed CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/).\n'
            ' * Changes: converted to a raw bitmap table.  This table (only) is CC BY-SA 4.0. */\n')
    f.write('static const unsigned char nilfont[256][16] = {\n')
    for c, rows in enumerate(glyphs):
        f.write('    {' + ','.join('0x%02X' % b for b in rows) + '},  /* %02X */\n' % c)
    f.write('};\n')

prev = Image.new('1', (32 * 9, 8 * 17), 0)
for c, rows in enumerate(glyphs):
    ox, oy = (c % 32) * 9, (c // 32) * 17
    for y, b in enumerate(rows):
        for x in range(8):
            if b & (0x80 >> x): prev.putpixel((ox + x, oy + y), 1)
prev.convert('L').resize((prev.width * 3, prev.height * 3), Image.NEAREST).save(OUT_PNG)
print('glyphs:', len(glyphs), 'empty (unexpected):', missing)
