#!/usr/bin/env python3
"""mklang.py - write dist/BBS/Text/Language/English.lng from the L("key", "text") calls in the source.

    python tools/mklang.py           write it
    python tools/mklang.py --check   exit 1 if the file in dist/ is out of date (or a key clashes)

Every L() call in src/node/*.c (plus src/common/lang.c's users, if any more are added to
SOURCES) is collected; the English text is the C string literal(s) after the key.  A key used
twice with different English is an error.  The .lng format is the one src/common/lang.c reads.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCES = [os.path.join('src', 'node')]
OUT = os.path.join(ROOT, 'dist', 'BBS', 'Text', 'Language', 'English.lng')

MODULES = {  # key prefix -> heading
    'node': 'Logon sequence (node.c)',
    'login': 'Login, new-user signup, logoff (login.c)',
    'term': 'Terminal: more/pause prompts, idle and time warnings, terminal setup (term.c)',
    'menu': 'Menus (menu.c) - the menu files themselves are BBS:Menus/<language>/*.mnu',
    'msg': 'Messages: areas, list, reader, editor, private mail (msgui.c)',
    'fse': 'Full-screen editor (fse.c)',
    'file': 'Files: areas, lists, transfers, CD-ROM browser, file tools (fileui.c)',
    'diz': 'FILE_ID.DIZ maker (diz.c)',
    'qwk': 'QWK offline mail (qwk.c)',
    'door': 'Doors (door.c) - door names come from Doors.cfg and are never translated',
    'cnetc': 'CNet C doors (cnetc.c)',
    'tele': 'Teleconference, paging, private chat (tele.c)',
    'comm': 'Bulletins, voting booth, finger, plans (community.c)',
    'misc': 'One-liners, last callers, who\'s online, user list, node messages, settings (misc.c)',
    'acs': 'Conferences (acs.c)',
    'sysop': 'Sysop menu (sysop.c)',
}

HEADER = """\
; NilBBS language file - English (the built-in text)
;
; Everything NilBBS says to callers comes from here.  To translate it:
;   1. copy this file to BBS:Text/Language/<Language>.lng, e.g. Deutsch.lng
;      (the name, up to 15 characters, is what callers pick from)
;   2. translate the text right of the "=" - never the key on the left
;   3. set "language = Deutsch" in BBS:Config/NilBBS.cfg for the board's default,
;      or let callers pick it (Your settings, G - and at signup)
;
; The rules:
;   key = text      the text runs to the end of the line.  Blanks around it are
;                   dropped - wrap it in "double quotes" to keep leading/trailing ones.
;   \\n              a new line   (\\t tab, \\\\ a backslash, \\xHH one raw CP437 byte)
;   |07 |15 ...     colour codes; |BN |UN |TL ... MCI codes - keep them where they fit
;   %s %d %ld ...   filled in by the BBS: keep EVERY one, in the SAME order, or the
;                   line is ignored and the English is shown instead
;   ; or #          at the start of a line: a comment
;   a line you delete (or never translate) simply stays English
;
; The file may be UTF-8 or Latin-1 (ISO-8859-1); both are turned into the BBS's own
; characters.  Hot keys stay the same in every language ([R]ead is still R), so keep
; the highlighted letter.  Column headings should keep their width.
;
; Not translated here on purpose: the custom ANSI/ASCII screens in BBS:Text (a
; translation may bring its own in BBS:Text/<Language>/), the menus (per language in
; BBS:Menus/<Language>/), door names, area names and anything else from the config.
;
; English itself is compiled into NilBBS - this file is the template and is NOT
; loaded for "English" callers.  To reword the English, copy it to another name
; (e.g. MyEnglish.lng) and make that the board's language.
;
; Generated by tools/mklang.py from the source - don't edit English.lng itself.
"""

IDENT = re.compile(r'[A-Za-z_][A-Za-z0-9_]*')


def tokens(src):
    i, n = 0, len(src)
    while i < n:
        c = src[i]
        if src.startswith('/*', i):
            j = src.find('*/', i + 2); i = n if j < 0 else j + 2; continue
        if src.startswith('//', i):
            j = src.find('\n', i); i = n if j < 0 else j; continue
        if c in '"\'':
            j = i + 1
            while j < n and src[j] != c:
                j += 2 if src[j] == '\\' else 1
            yield ('str' if c == '"' else 'chr', src[i:j + 1], i); i = j + 1; continue
        m = IDENT.match(src, i)
        if m:
            yield ('id', m.group(), i); i = m.end(); continue
        if c.isspace():
            i += 1; continue
        yield ('op', c, i); i += 1


def c_unescape(body):
    out, i = [], 0
    while i < len(body):
        ch = body[i]
        if ch != '\\':
            out.append(ch); i += 1; continue
        d = body[i + 1]
        if d in 'ntr':
            out.append({'n': '\n', 't': '\t', 'r': '\r'}[d]); i += 2
        elif d == 'x':
            j = i + 2
            while j < len(body) and body[j] in '0123456789abcdefABCDEF': j += 1
            out.append(chr(int(body[i + 2:j], 16) & 255)); i = j
        elif d in '01234567':
            j = i + 1
            while j < len(body) and j < i + 4 and body[j] in '01234567': j += 1
            out.append(chr(int(body[i + 1:j], 8) & 255)); i = j
        else:
            out.append(d); i += 2
    return ''.join(out)


def lng_escape(text):
    out = []
    for ch in text:
        o = ord(ch)
        if ch == '\n': out.append('\\n')
        elif ch == '\t': out.append('\\t')
        elif ch == '\\': out.append('\\\\')
        elif o < 32 or o >= 127: out.append('\\x%02X' % o)
        else: out.append(ch)
    s = ''.join(out)
    if s != s.strip(' ') or s == '' or (s.startswith('"') and s.endswith('"')):
        s = '"' + s + '"'
    return s


def collect():
    found = {}      # key -> (text, where)
    order = []
    errors = []
    for d in SOURCES:
        for fn in sorted(os.listdir(os.path.join(ROOT, d))):
            if not fn.endswith('.c'): continue
            path = os.path.join(ROOT, d, fn)
            src = open(path, encoding='latin-1').read()
            toks = list(tokens(src))
            for i in range(len(toks) - 3):
                if toks[i][:2] != ('id', 'L') or toks[i + 1][1] != '(' or toks[i + 2][0] != 'str' or toks[i + 3][1] != ',':
                    continue
                if i and toks[i - 1][1] in ('.', '>'): continue
                key = toks[i + 2][1][1:-1]
                where = '%s:%d' % (fn, src.count('\n', 0, toks[i][2]) + 1)
                j, parts = i + 4, []
                while toks[j][0] == 'str':
                    parts.append(c_unescape(toks[j][1][1:-1])); j += 1
                if not parts or toks[j][1] != ')':
                    errors.append('%s: L("%s", ...) - the English must be string literals only' % (where, key)); continue
                if not re.fullmatch(r'[A-Za-z0-9_.\-]+', key):
                    errors.append('%s: bad key "%s"' % (where, key)); continue
                text = ''.join(parts)
                if key in found:
                    if found[key][0] != text:
                        errors.append('%s: key "%s" already used at %s with different English' % (where, key, found[key][1]))
                    continue
                found[key] = (text, where)
                order.append(key)
    return found, order, errors


def render(found, order):
    lines = [HEADER]
    groups = {}
    for k in order:
        groups.setdefault(k.split('.')[0], []).append(k)
    known = [m for m in MODULES if m in groups] + sorted(m for m in groups if m not in MODULES)
    for m in known:
        lines.append('')
        lines.append('; ' + '-' * 76)
        lines.append('; ' + MODULES.get(m, m))
        lines.append('; ' + '-' * 76)
        for k in groups[m]:
            lines.append('%s = %s' % (k, lng_escape(found[k][0])))
    return '\n'.join(lines) + '\n'


def roundtrip(text, found):
    """read the rendered file back the way the node does (langcheck.parse = lang.c): same text?"""
    import tempfile
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import langcheck
    fd, tmp = tempfile.mkstemp(suffix='.lng')
    with os.fdopen(fd, 'w', encoding='latin-1', newline='\n') as f:
        f.write(text)
    try:
        entries, dups, bad = langcheck.parse(tmp)
    finally:
        os.remove(tmp)
    raw = lambda s: re.sub(r'[\x01-\x1f\x7f-\xff]', lambda m: m.group() if m.group() in '\n\t' else '\\x%02X' % ord(m.group()), s)
    wrong = [k for k, (t, _) in found.items() if entries.get(k) != raw(t)]
    if bad or dups or wrong:
        print('ERROR round trip: %d bad lines, %d dups, %d changed (%s)' % (len(bad), len(dups), len(wrong), ', '.join(wrong[:5])))
        sys.exit(1)


def main():
    found, order, errors = collect()
    for e in errors: print('ERROR', e)
    if errors: sys.exit(1)
    text = render(found, order)
    roundtrip(text, found)
    if '--check' in sys.argv:
        old = open(OUT, encoding='latin-1').read() if os.path.exists(OUT) else ''
        if old != text:
            print('%s is out of date - run tools/mklang.py' % OUT); sys.exit(1)
        print('English.lng is up to date (%d keys)' % len(order)); return
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='latin-1', newline='\n') as f:
        f.write(text)
    print('wrote %s: %d keys' % (os.path.relpath(OUT, ROOT), len(order)))


if __name__ == '__main__':
    main()
